[window]
decorations = "Full"

[shell]
program = "/usr/bin/zsh"

[keyboard]
bindings = [
{ key = "N",         mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "ArrowLeft", mods = "Control", action = "CreateNewWindow" },
{ key = "t",         mods = "Control", action = "CreateNewTab" },
{ key = "Key1",      mods = "Alt",     action = "SelectTab1" },
{ key = "Key2",      mods = "Alt",     action = "SelectTab2" },
{ key = "Key3",      mods = "Alt",     action = "SelectTab3" },
{ key = "Key4",      mods = "Alt",     action = "SelectTab4" },
{ key = "Key5",      mods = "Alt",     action = "SelectTab5" },
{ key = "Key6",      mods = "Alt",     action = "SelectTab6" },
{ key = "Key7",      mods = "Alt",     action = "SelectTab7" },
]